name: CI

on: [push, fork, pull_request, workflow_dispatch]

jobs:
  typos:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: crate-ci/typos@master

  check:
    strategy:
      matrix:
        os: [ubuntu, macos]
        py: [3.12, 3.13]
      fail-fast: false
    runs-on: ${{ matrix.os }}-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.py }}
      - name: Install dependencies
        run: |
          pip install uv
          uv pip install -r pyproject.toml --system
          yarn global add pyright
      - name: Check code quality
        run: |
          ruff format --check --diff
          ruff check --diff
      - name: Check typing
        run: |
          pyright
