name: CI

on: [push, fork, pull_request, workflow_dispatch]

jobs:
  typos:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: crate-ci/typos@master

  check:
    strategy:
      matrix:
        os: [ubuntu, macos]
        py: [3.12, 3.13]
      fail-fast: false
    runs-on: ${{ matrix.os }}-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: astral-sh/setup-uv@v6
        with:
          python-version: ${{ matrix.py }}
      - name: Install dependencies
        run: |
          uv sync --color always
      - name: Check code quality
        run: |
          ruff format --check --diff
          ruff check --diff
      - uses: oven-sh/setup-bun@v2
      - name: Check typing
        run: |
          bunx pyright
